apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: applications.hubify.io
spec:
    group: hubify.io
    names:
        categories: []
        kind: Application
        plural: applications
        shortNames:
        - app
        singular: application
    scope: Namespaced
    versions:
    - name: v1
      additionalPrinterColumns: []
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
            title: Application 
            type: object
            description: |
                Application is the link for the applications which will be
                shown in the hubify dashboard.
            properties:
                spec:
                    description: |-
                        Spec is the spec for the application.
                    properties:
                        name:
                          type: string
                        version:
                          type: string
                        description:
                          type: string
                        icon:
                          type: string
                        url:
                          type: string
                        categories:
                          type: array
                          items:
                            type: string
                    required:
                      - name
                      - url
                    type: object
                status:
                    description: |-
                        Status is the status for the application.
                    properties:
                        installed:
                          type: boolean
                    required:
                      - installed
                    type: object
            required:
              - spec

