---
# Scoped service account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tenement
  namespace: tenement
automountServiceAccountToken: true
---
# Access for the service account (cluster scoped list)
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tenement 
rules:
  - apiGroups:
    - apps
    resources:
    - deployments
    - services
    verbs:
    - get
    - watch
    - list

---
# Binding the role to the account
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tenement
subjects:
- kind: ServiceAccount
  name: tenement
  namespace: tenement
roleRef:
  kind: ClusterRole
  name: tenement
  apiGroup: rbac.authorization.k8s.io
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: tenement-controller
  namespace: tenement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tenement-controller
  template:
    metadata:
      labels:
        app: tenement-controller
    spec:
      serviceAccountName: tenement
      containers:
        - name: tenement-controller
          image: tenement-controller
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: frontend 
  namespace: tenement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend 
    spec:
      containers:
        - name: frontend 
          image: frontend 
          ports:
            - name: http
              containerPort: 5173
              protocol: TCP
