---
# Scoped service account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hubify
  namespace: hubify
automountServiceAccountToken: true
---
# Access for the service account (cluster scoped list)
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hubify 
rules:
  - apiGroups:
    - ""
    - "hubify.io"
    resources:
    - deployments
    - services
    - applications
    - commands
    verbs:
    - get
    - watch
    - list
---
# Binding the role to the account
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hubify
subjects:
- kind: ServiceAccount
  name: hubify
  namespace: hubify
roleRef:
  kind: ClusterRole
  name: hubify
  apiGroup: rbac.authorization.k8s.io
