apiVersion: v1
kind: Service
metadata:
  name: hubify-controller
  namespace: hubify
  labels:
    kubernetes.io/name: "hubify-controller"
spec:
  selector:
    app: hubify-controller
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 3000
    targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: hubify-frontend
  namespace: hubify
  labels:
    kubernetes.io/name: "frontend"
spec:
  selector:
    app: frontend 
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 5173
    targetPort: 5173
